### ISSUE TITLE
[DEVICE-TESTED] Conga 2290

### ISSUE THREAD

**Issue by Lumanet** [alemuro/ha-cecotec-conga#12]
**Device model**
Please set which Conga device have you tested
Problem with credentials when configuring the integration:
<img width="371" alt="Captura de Pantalla 2022-09-22 a las 8 47 02" src="https://user-images.githubusercontent.com/1859390/191677701-ca2ebb4e-61c7-4b00-a8e1-abe2a2dce323.png">

**Comment by alemuro** [comment]
Hello @Lumanet ! Thanks for reporting this! 
Seems Cecotec has different "endpoints" depending on the model. I'll try to get those endpoints and I'll ping you later🤞 🤞 

Regards,

**Comment by Lumanet** [comment]
Any solution?

**Comment by alemuro** [comment]
Unfortunately, I tested the app and I tried to integrate it with this integration, but I didn't manage to do it. 
Seems only Cecotec Conga 5290 works with AWS services 😞 

Sorry for this late response, I wanted to find a solution before answering. You can try Freeconga or Badconga.

I'm opening the PR #21  to update the README and make it clear now.

**Comment by ayoze** [comment]
> Unfortunately, I tested the app and I tried to integrate it with this integration, but I didn't manage to do it. Seems only Cecotec Conga 5290 works with AWS services 😞
> 
> Sorry for this late response, I wanted to find a solution before answering. You can try Freeconga or Badconga.
> 
> I'm opening the PR [#21](https://github.com/alemuro/ha-cecotec-conga/pull/21) to update the README and make it clear now.

Hello Aleix, and what's the problem with this? I mean, why is needed that the services are hosted in AWS? I would love to try to help with this.
