### ISSUE TITLE
[DEVICE-TESTED] Conga 4690

### ISSUE THREAD

**Issue by Nofre** [alemuro/ha-cecotec-conga#13]
Conga 4690 has also login problems, probably due to different endpoints, as you must use a specific app only for this model.

**Comment by Soyde** [comment]
same login problems here with conga 4690

**Comment by Soyde** [comment]
Please tell me how can I help you

**Comment by mineroloco55** [comment]
I have a 4690 and i do not know if i need make any think in the robot. Can you explain ? This addon go to the web? Or is it fully local ?
I would like to help you but i don't know how

**Comment by barrizgz** [comment]
Me tested too with a 4690 and can't login

**Comment by Soyde** [comment]
¿Acaso estas integración sirve para algo más que simplemente el modelo que ha probado el autor del addon? Porque sinceramente, no le veo ni movimiento al repositorio, ni futuro....
No quedará otra que quitar el addon de mi instalación, porque esto no da esperanzas de aunar las congas que no son compatibles con freeconga como indica el autor....

**Comment by alemuro** [comment]
Unfortunately, I tested the app and I tried to integrate it with this integration, but I didn't manage to do it. 
Seems only Cecotec Conga 5290 works with AWS services 😞 

Sorry for this late response, I wanted to find a solution before answering. You can try Freeconga or Badconga.

I'm opening the PR #21  to update the README and make it clear now.
