### ISSUE TITLE
[DEVICE-TESTED] Conga 5090

### ISSUE THREAD

**Issue by jcorreaes** [alemuro/ha-cecotec-conga#14]
**Device model**
Conga 5090
Login issues, perhaps different endpoints.

**Comment by alemuro** [comment]
Unfortunately, I tested the app and I tried to integrate it with this integration, but I didn't manage to do it. 
Seems only Cecotec Conga 5290 works with AWS services 😞 

Sorry for this late response, I wanted to find a solution. 

I'm opening the PR #21  to update the README and make it clear now.
