### ISSUE TITLE
[DEVICE-TESTED] Credential fail

### ISSUE THREAD

**Issue by Nismonx** [alemuro/ha-cecotec-conga#18]
**Describe the bug**
After instalation, when prompted to enter credentials it returns 'invalid user'

**To Reproduce**

**Expected behavior**

**Screenshots**
![Screenshot_20221020-214910_Home Assistant](https://user-images.githubusercontent.com/62077532/197055488-5a1c47fb-b512-4ea0-ab75-3941df1b1d1b.jpg)

**Desktop (please complete the following information):**
 

**Smartphone (please complete the following information):**
 - Device: Pi4
 - OS: Home assistant OS
 - Browser App
 - Version latest

**Additional context**
Conga 4090

device connects via different end points:
/mnt/UDISK/config/sysConfig.ini
[Sys_Config]
server_cmd_address=cecotec.das.3irobotix.net
server_map_address=cecotec.das.3irobotix.net
server_log_address=cecotec.log.3irobotix.net
server_ota_address=cecotec.ota.3irobotix.net
server_down_address=cecotec.download.3irobotix.net
server_ssl_cmd_port=5010
server_ssl_map_port=5030
server_ssl_enable=0
server_cmd_port=4010
server_map_port=4030
server_sync_time_port=4050
server_log_port=21
server_ota_check_port=5000
server_ota_download_port=2300
wlan_port=8111
wlan_broad_port=8888
deviceFirmsID=1003
deviceType=20
languageType=2
hardwareRtc=1
timezoneSec=28800
ctrl_version=V4.0

extra details:
[Device_Config]
software_version=S3.3.8.23.42R
hardware_version=1.0.1
robot_app_version=5
algorithm_version=2.0.1.180301_Alpha23
stm32_version=1.0.0_18112142
lidar_version=LIDAR_VERSION_UNKNOW

works with 5000 and 4000 series apps

**Comment by alemuro** [comment]
Device 3090 is not currently supported. You can try Freeconga or Badconga.

I'm opening the PR #21  to update the README and make it clear now.

**Comment by Nismonx** [comment]
Ok, no worries but it's 4090 not 3090.

👍
