### ISSUE TITLE
[DEVICE-TESTED] Conga 3090

### ISSUE THREAD

**Issue by Pelukosa** [alemuro/ha-cecotec-conga#19]
**Device model**
Please set which Conga device have you tested

**Comment by alemuro** [comment]
Unfortunately, I tested the app and I tried to integrate it with this integration, but I didn't manage to do it. 
Seems only Cecotec Conga 5290 works with AWS services 😞 

Sorry for this late response, I wanted to find a solution before answering. You can try Freeconga or Badconga.

I'm opening the PR #21  to update the README and make it clear now.
